2025-10-27 18:02:04,874 INFO    MainThread:44756 [wandb_setup.py:_flush():81] Current SDK version is 0.22.2
2025-10-27 18:02:04,874 INFO    MainThread:44756 [wandb_setup.py:_flush():81] Configure stats pid to 44756
2025-10-27 18:02:04,874 INFO    MainThread:44756 [wandb_setup.py:_flush():81] Loading settings from C:\Users\benpr\.config\wandb\settings
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_setup.py:_flush():81] Loading settings from C:\Users\benpr\OneDrive\Documents\Software Development\Training\Learning\Athena 1 Recursive Preparing\v1\wandb\settings
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_init.py:setup_run_log_directory():705] Logging user logs to C:\Users\benpr\OneDrive\Documents\Software Development\Training\Learning\Athena 1 Recursive Preparing\v1\wandb\offline-run-20251027_180204-rd4baakd\logs\debug.log
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_init.py:setup_run_log_directory():706] Logging internal logs to C:\Users\benpr\OneDrive\Documents\Software Development\Training\Learning\Athena 1 Recursive Preparing\v1\wandb\offline-run-20251027_180204-rd4baakd\logs\debug-internal.log
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_init.py:init():832] calling init triggers
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_init.py:init():837] wandb.init called with sweep_config: {}
config: {'arch': {'name': 'recursive_reasoning.athena_trm@AthenaTRM', 'loss': {'name': 'losses@ACTLossHead', 'loss_type': 'stablemax_cross_entropy'}, 'hidden_size': 128, 'num_heads': 4, 'expansion': 2.0, 'H_cycles': 2, 'L_cycles': 2, 'puzzle_emb_ndim': 0, 'reasoning_seq_len': 32, 'reasoning_vocab_size': 32000, 'enable_reasoning_stream': True, 'post_refinement_steps': 4, 'halt_max_steps': 6, 'force_min_steps': 4, 'halt_exploration_prob': 0.08, 'forward_dtype': 'float32'}, 'data_paths': ['data_examples\\smoke\\processed_3'], 'data_paths_test': [], 'evaluators': [{'name': 'text@PerplexityEvaluator'}], 'global_batch_size': 16, 'epochs': 5, 'lr': 0.0005, 'lr_min_ratio': 0.1, 'lr_warmup_steps': 5, 'weight_decay': 0.1, 'beta1': 0.9, 'beta2': 0.95, 'puzzle_emb_lr': 0.0002, 'puzzle_emb_weight_decay': 0.1, 'project_name': 'Athena-v1', 'run_name': 'smoke_test', 'load_checkpoint': None, 'checkpoint_path': 'checkpoints\\Athena-v1\\smoke_test', 'seed': 0, 'checkpoint_every_eval': True, 'eval_interval': 5, 'min_eval_interval': 2, 'eval_save_outputs': ['logits', 'reasoning_logits'], 'ema': False, 'ema_rate': 0.9995, 'freeze_weights': False, '_wandb': {}}
2025-10-27 18:02:04,875 INFO    MainThread:44756 [wandb_init.py:init():880] starting backend
2025-10-27 18:02:07,288 INFO    MainThread:44756 [wandb_init.py:init():883] sending inform_init request
2025-10-27 18:02:07,503 INFO    MainThread:44756 [wandb_init.py:init():891] backend started and connected
2025-10-27 18:02:07,505 INFO    MainThread:44756 [wandb_init.py:init():961] updated telemetry
2025-10-27 18:02:07,507 INFO    MainThread:44756 [wandb_init.py:init():985] communicating run to backend with 90.0 second timeout
2025-10-27 18:02:07,896 INFO    MainThread:44756 [wandb_init.py:init():1036] starting run threads in backend
2025-10-27 18:02:08,388 INFO    MainThread:44756 [wandb_run.py:_console_start():2509] atexit reg
2025-10-27 18:02:08,388 INFO    MainThread:44756 [wandb_run.py:_redirect():2357] redirect: wrap_raw
2025-10-27 18:02:08,388 INFO    MainThread:44756 [wandb_run.py:_redirect():2426] Wrapping output streams.
2025-10-27 18:02:08,389 INFO    MainThread:44756 [wandb_run.py:_redirect():2449] Redirects installed.
2025-10-27 18:02:08,394 INFO    MainThread:44756 [wandb_init.py:init():1076] run started, returning control to user process
2025-10-27 18:02:08,503 INFO    MainThread:44756 [wandb_run.py:_config_callback():1392] config_cb None None {'_wandb': {'code_path': 'source-Athena-v1-scripts_smoke_test.py'}}
2025-10-27 18:02:08,894 INFO    wandb-AsyncioManager-main:44756 [service_client.py:_forward_responses():80] Reached EOF.
2025-10-27 18:02:08,894 INFO    wandb-AsyncioManager-main:44756 [mailbox.py:close():137] Closing mailbox, abandoning 0 handles.
2025-10-27 18:02:08,937 ERROR   MainThread:44756 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_run.py", line 2430, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\wandb_run.py", line 1595, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\interface\interface.py", line 802, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\interface\interface_shared.py", line 37, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\interface\interface_sock.py", line 43, in _publish
    self._asyncer.run(lambda: self._client.publish(request))
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\asyncio_manager.py", line 136, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\asyncio_manager.py", line 219, in _wrap
    return await fn()
           ^^^^^^^^^^
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\service\service_client.py", line 38, in publish
    await self._send_server_request(request)
  File "C:\Users\benpr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\wandb\sdk\lib\service\service_client.py", line 64, in _send_server_request
    await self._writer.drain()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
